dist: trusty
sudo: required
language: bash
before_install:
 - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash

notifications:
  slack:
    rooms:
      secure: XXw9hl4JlIxZYvC3uCsEEzL/OQ7eBQ2sFbNaP7KloWKIr1usTFvw2PX+6kwoC0fH2NvcGMqh5kTGgnqS7HadqCYIseJXSXIhjFJhnxr5kdZnNEiomYojvOW5fVIPtQmT9dGFumY7v1gCOuhE/a3QEIQpcNS0m74ayyMLwiibX+hr04LuPsAyRi2Z2DSLjTUb9fz1ee/GRyt1pLR27mor3kOsRnVlvWIjgcLbMXEUaKYwGL/wOPDcQyOVRDiIetHnZgR17wftuOWTKa3HvHlXap9Jw0wjlrYP55yszDPt0DOOwQRgeyBdCOeVwOXHQ57dkxkFRQrL3jaECuEsl5Gi2p03oBE+KX5eaPWg34sL/7Or6L1OfPch42SrhQKEZa/696j/T85rBbP2U0kqm+OqWLggMNV0ewUNUaFI7KBiqu5LrFW+meOWuDQvstnXJbvdO8grO0syIIJ12x0yfN5+biTSPzzpdsFmQmX2JxqPQTZIR8fSn8SCqm/eKn9HsGdJN2jmfHJQK/5403BsdEAmKq7V8XdQftzkjuqkSO/mdtlO9Se5DZhzUZNatabPYca460/tJFVsOIq55dVVqtuYf6sgE3l3byJX7NlSZD1quZvGJjA3Q0tftQ1A0beo1vVU6qarESXb/2OmOsqAr1XaZ1SCTK1krJMKvkEhWL8xBNU=
