global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#sergey_makeev'
