version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_IMG_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_IMG_VER}
    ports:
      - ${PUBLISHED_PORT}:9292/tcp
      - 9292:9292/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:${POST_IMG_VER}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    image: ${USERNAME}/comment:${COMMENT_IMG_VER}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      front_net:
        aliases:
          - prometheus
      back_net:
        aliases:
          - prometheus

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    networks:
      back_net:
        aliases:
          - node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 10.0.100.0/24
  back_net:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 10.0.200.0/24
