version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_IMG_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_IMG_VER}
    command: puma --debug -w 2
    ports:
      - ${PUBLISHED_PORT}:9292/tcp
      - 9292:9292/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_IMG_VER}
    networks:
      back_net:
        aliases:
          - pos
      front_net:
        aliases:
          - post
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMG_VER}
        volumes:
            - type: bind
                source: ./comment
                target: /app
    command: puma --debug -w 2

    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  front_net:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 10.0.100.0/24
  back_net:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 10.0.200.0/24
